# Generated by Django 2.2 on 2020-05-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200515_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc',
            new_name='document',
        ),
    ]
